name: Landing zone request form
description: Request Landing Zone
title: "[lz request]: "
labels: ["request"]
assignees:
  - lawrencek76
body:
  - type: input
    attributes:
      label: Application Name
      description: What is the name of the application?
      placeholder: Enter your answer
    validations:
      required: true
  - type: dropdown
    attributes:
      label: PMO
      description: What PMO will support the application?
      multiple: false
      options:
        - OCIO (Default)
        - HRS
        - RS
        - Other (Specify in other info below)
    validations:
      required: true
  - type: input
    attributes:
      label: Application Owner
      description: Provide the names(s) of the Application Owners?
      placeholder: Enter your answer
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Environment Type
      description: What type of environment is this?
      multiple: false
      options:
        - Non-Production
        - Production
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Environment Size
      description: What size IP range will be rquired?
      multiple: false
      options:
        - Small
        - Medium
        - Large
        - Other (Specify in other info below)
    validations:
      required: true
  - type: textarea
    attributes:
      label: Other Info
      description: "Other Info (attach a file by dropping it in this area)"
      value: |
        Other PMO: 
        Other Size:
      render: markdown
    validations:
      required: true
  - type: markdown
    attributes:
      value: "Thanks for completing our form!"
